apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-for-product-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-for-product-microservice
  template:
    metadata:
      labels:
        app: postgres-for-product-microservice
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: rsr
        - name: POSTGRES_DB
          value: ms-product
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-for-product-microservice
spec:
  selector:
    app: postgres-for-product-microservice
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: LoadBalancer
